apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-patcher
subjects:
  - kind: ServiceAccount
    name: configmap-patcher
roleRef:
  kind: Role
  name: configmap-patcher
  apiGroup: rbac.authorization.k8s.io
